### ISSUE TITLE
Can you check it?

### ISSUE THREAD

**Issue by KHRIND** [Fantaso/whatsapp-web#4]
DevTools listening on ws://127.0.0.1:53117/devtools/browser/7be00894-9b32-4845-b0c1-e04c8d2af228
[16628:15092:1121/172315.127:ERROR:device_event_log_impl.cc(211)] [17:23:15.127] Bluetooth: bluetooth_adapter_winrt.cc:1073 Getting Default Adapter failed.
Traceback (most recent call last):
  File "c:\Users\yusuf\OneDrive\Masaüstü\python\whatsapp.py", line 31, in <module>
    opened_chats = pane_page.opened_chats
  File "C:\Users\yusuf\AppData\Local\Programs\Python\Python38\lib\site-packages\simon\chats\elements.py", line 30, in __get__
    WebDriverWait(driver, 100).until(
  File "C:\Users\yusuf\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by z404** [comment]
+1, same issue

**Comment by matiasleoni** [comment]
same problem for me. The browser opens, the box is unchecked, I log in with the QR but then it stops working and after some seconds the Timeout exception occurs.

**Comment by DanielChiluisa011** [comment]
+3, same issue

**Comment by z404** [comment]
Apparently, whatsapp web has changed thier css styling after the api was made, and the api was never updated after that. There are other wrappers that work better. I dunno if im allowed to post the links here, but i think this project has been abandonded. OP you can close the issue i suppose

**Comment by matiasleoni** [comment]
> Apparently, whatsapp web has changed thier css styling after the api was made, and the api was never updated after that. There are other wrappers that work better. I dunno if im allowed to post the links here, but i think this project has been abandonded. OP you can close the issue i suppose

z404, could you recommend here or privately other wrappers that work better developed in python?

**Comment by z404** [comment]
> 
> 
> > Apparently, whatsapp web has changed thier css styling after the api was made, and the api was never updated after that. There are other wrappers that work better. I dunno if im allowed to post the links here, but i think this project has been abandonded. OP you can close the issue i suppose
> 
> z404, could you recommend here or privately other wrappers that work better developed in python?

https://github.com/mukulhase/WebWhatsapp-Wrapper (Install from source, the pip version is outdated) (Docker installation not required)

Happy coding

**Comment by AgustinPardo** [comment]
same issue!

**Comment by urieltm** [comment]
> 
> 
> > > Apparently, whatsapp web has changed thier css styling after the api was made, and the api was never updated after that. There are other wrappers that work better. I dunno if im allowed to post the links here, but i think this project has been abandonded. OP you can close the issue i suppose
> > 
> > 
> > z404, could you recommend here or privately other wrappers that work better developed in python?
> 
> https://github.com/mukulhase/WebWhatsapp-Wrapper (Install from source, the pip version is outdated) (Docker installation not required)
> 
> Happy coding

How do i install from source?

**Comment by z404** [comment]
> 
> 
> > > > Apparently, whatsapp web has changed thier css styling after the api was made, and the api was never updated after that. There are other wrappers that work better. I dunno if im allowed to post the links here, but i think this project has been abandonded. OP you can close the issue i suppose
> > > 
> > > 
> > > z404, could you recommend here or privately other wrappers that work better developed in python?
> > 
> > 
> > https://github.com/mukulhase/WebWhatsapp-Wrapper (Install from source, the pip version is outdated) (Docker installation not required)
> > Happy coding
> 
> How do i install from source?

All you gotta do it download the repository, and run `python setup.py install` when inside the repository
