### ISSUE TITLE
ModuleNotFoundError: No module named 'simon.accounts'; 'simon' is not a package

### ISSUE THREAD

**Issue by ravi7874** [Fantaso/whatsapp-web#7]
Traceback (most recent call last):
  File "C:\Users\ravic\Desktop\python\simon.py", line 5, in <module>
    from simon.accounts.pages import LoginPage
  File "C:\Users\ravic\Desktop\python\simon.py", line 5, in <module>
    from simon.accounts.pages import LoginPage
ModuleNotFoundError: No module named 'simon.accounts'; 'simon' is not a package

I have uninstalled and installed simon 3 times but still gets same error.
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Only Python 3.9.5 is installed in Windows 10 64 bit

**Comment by ariannamorettj** [comment]
I have the same issue, did anybody else mention it? Thank you in advance @Fantaso

**Comment by RyugaD** [comment]
Try installing the whatsapp-web library using the following command: pip install whatsapp-web
